apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-pod-nginx-web2
spec:
  replicas: 5
  template:
    metadata:
      name: pod-nginx-web2
      labels:
        app: nginx-web2
    spec:
      containers:
        - name: container-nginx-web2
          image: matheusscosta/nginx:nginx-web2
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: nginx-web2        


# Service para comunicação interna      
---
apiVersion: v1      
kind: Service
metadata:
  name: svc-nginx-web2
spec:
  type: ClusterIP
  selector:
    app: nginx-web2
  ports:
    - port: 443         # Porta que receberá a requisição
      targetPort: 80    # Porta em que o service vai "despachar" a requisição


# Service para acesso externo
apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport-nginx-web2
spec:
  type: NodePort
  selector:
    app:  nginx-web2
  ports:
    - port: 443
      targetPort: 80
      nodePort: 31000  
