apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx-web1
spec:
  replicas: 5
  template:
    metadata:
      name: pod-nginx-web1
      labels:
        app: nginx-web1
    spec:
      containers:  
        - name: container-nginx-web1
          image: matheusscosta/nginx:nginx-web1
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: nginx-web1

# Service para comunicação interna      
---
apiVersion: v1      
kind: Service
metadata:
  name: svc-nginx-web1
spec:
  type: ClusterIP
  selector:
    app: nginx-web1
  ports:
    - port: 443         # Porta que receberá a requisição
      targetPort: 80    # Porta em que o service vai "despachar" a requisição



---

# Service para acesso externo
apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport-nginx-web1
spec:
  type: NodePort
  selector:
    app:  nginx-web1
  ports:
    - port: 443
      targetPort: 80
      nodePort: 30000
